export type ThemeId =
  | 'inventory-sync'
  | 'industrial-amber'
  | 'alpine-cyan'
  | 'emerald-mint'
  | 'highvis-orange'
  | 'corporate-navy'
  | 'obsidian-gold'
  | 'nordic-indigo'
  | 'cyber-matrix'
  | 'copper-espresso'
  | 'royal-sapphire'
  | 'paper-slate'
  | 'pacific-teal'
  | 'sunset-terracotta'
  | 'forest-sage'
  | 'violet-platinum';

export interface ThemeConfig {
  id: ThemeId;
  name: string;
  subtitle: string;
  mode: 'dark' | 'light';
  previewColor: string; // Tailwind bg color for preview dot
  
  // Outer App Layout
  appBg: string;
  appText: string;
  
  // Header / Navbar
  headerBg: string;
  headerBorder: string;
  headerText: string;
  logoBg: string;
  logoText: string;
  badgeBg: string;
  badgeText: string;
  badgeBorder: string;
  
  // Cards & Containers
  cardBg: string;
  cardBorder: string;
  cardTextHeader: string;
  cardTextValue: string;
  
  // Table
  tableHeaderBg: string;
  tableHeaderText: string;
  tableBorder: string;
  tableRowHover: string;
  
  // Accent & Priority Badge
  priorityBadgeBg: string;
  priorityBadgeText: string;
  accentButtonBg: string;
  accentButtonHover: string;
  accentButtonText: string;
  
  // Alert & Status Highlighting
  shortageCardBg: string;
  shortageBorder: string;
  shortageText: string;
  
  coveredCardBg: string;
  coveredBorder: string;
  coveredText: string;
  
  // Modals
  modalBg: string;
  modalBorder: string;
  modalText: string;
}

export const Themes: Record<ThemeId, ThemeConfig> = {
  'inventory-sync': {
    id: 'inventory-sync',
    name: '1. InventorySync Ultra-Clean Light',
    subtitle: 'Modern Clean ERP Dashboard (Crisp Light Canvas & Dark Navy Header Table)',
    mode: 'light',
    previewColor: 'bg-blue-600',
    appBg: 'bg-[#F8FAFC] text-slate-900',
    appText: 'text-slate-900',
    headerBg: 'bg-white',
    headerBorder: 'border-slate-200/80',
    headerText: 'text-slate-900',
    logoBg: 'bg-blue-600 text-white shadow-xs',
    logoText: 'text-white',
    badgeBg: 'bg-slate-100',
    badgeText: 'text-slate-600 font-medium',
    badgeBorder: 'border-slate-200',
    cardBg: 'bg-white',
    cardBorder: 'border-slate-200/80',
    cardTextHeader: 'text-slate-500 font-semibold',
    cardTextValue: 'text-slate-900',
    tableHeaderBg: 'bg-[#0F172A]',
    tableHeaderText: 'text-white font-bold',
    tableBorder: 'border-slate-200',
    tableRowHover: 'hover:bg-slate-50/80',
    priorityBadgeBg: 'bg-[#0F172A]',
    priorityBadgeText: 'text-white font-mono',
    accentButtonBg: 'bg-blue-600',
    accentButtonHover: 'hover:bg-blue-700',
    accentButtonText: 'text-white font-semibold',
    shortageCardBg: 'bg-white',
    shortageBorder: 'border-rose-200',
    shortageText: 'text-rose-600 font-bold',
    coveredCardBg: 'bg-white',
    coveredBorder: 'border-emerald-200',
    coveredText: 'text-emerald-600 font-bold',
    modalBg: 'bg-white',
    modalBorder: 'border-slate-200',
    modalText: 'text-slate-900'
  },

  'industrial-amber': {
    id: 'industrial-amber',
    name: '1. Industrial Slate & Amber',
    subtitle: 'Rugged Rhino-Rack Sydney DC Industrial Style (Default)',
    mode: 'dark',
    previewColor: 'bg-amber-500',
    appBg: 'bg-slate-950 text-slate-100',
    appText: 'text-slate-100',
    headerBg: 'bg-slate-900',
    headerBorder: 'border-slate-800',
    headerText: 'text-white',
    logoBg: 'bg-gradient-to-tr from-amber-500 to-amber-600',
    logoText: 'text-slate-950',
    badgeBg: 'bg-amber-500/10',
    badgeText: 'text-amber-400',
    badgeBorder: 'border-amber-500/30',
    cardBg: 'bg-slate-900',
    cardBorder: 'border-slate-800',
    cardTextHeader: 'text-slate-400',
    cardTextValue: 'text-white',
    tableHeaderBg: 'bg-slate-900',
    tableHeaderText: 'text-slate-300',
    tableBorder: 'border-slate-800',
    tableRowHover: 'hover:bg-slate-800/60',
    priorityBadgeBg: 'bg-slate-900',
    priorityBadgeText: 'text-amber-400',
    accentButtonBg: 'bg-amber-600',
    accentButtonHover: 'hover:bg-amber-500',
    accentButtonText: 'text-slate-950 font-bold',
    shortageCardBg: 'bg-slate-900 bg-gradient-to-b from-amber-950/20 to-transparent',
    shortageBorder: 'border-amber-900/50',
    shortageText: 'text-amber-400',
    coveredCardBg: 'bg-slate-900',
    coveredBorder: 'border-emerald-900/50',
    coveredText: 'text-emerald-400',
    modalBg: 'bg-slate-900',
    modalBorder: 'border-slate-800',
    modalText: 'text-slate-100'
  },

  'alpine-cyan': {
    id: 'alpine-cyan',
    name: '2. Alpine Steel & Electric Cyan',
    subtitle: 'Aerospace & Cold Storage Supply Chain Precision',
    mode: 'dark',
    previewColor: 'bg-cyan-400',
    appBg: 'bg-slate-950 text-slate-100',
    appText: 'text-slate-100',
    headerBg: 'bg-slate-900',
    headerBorder: 'border-cyan-900/50',
    headerText: 'text-white',
    logoBg: 'bg-gradient-to-tr from-cyan-400 to-blue-600',
    logoText: 'text-slate-950',
    badgeBg: 'bg-cyan-500/10',
    badgeText: 'text-cyan-300',
    badgeBorder: 'border-cyan-500/30',
    cardBg: 'bg-slate-900',
    cardBorder: 'border-slate-800',
    cardTextHeader: 'text-slate-400',
    cardTextValue: 'text-cyan-50',
    tableHeaderBg: 'bg-slate-900',
    tableHeaderText: 'text-cyan-200',
    tableBorder: 'border-slate-800',
    tableRowHover: 'hover:bg-cyan-950/30',
    priorityBadgeBg: 'bg-cyan-950',
    priorityBadgeText: 'text-cyan-300',
    accentButtonBg: 'bg-cyan-500',
    accentButtonHover: 'hover:bg-cyan-400',
    accentButtonText: 'text-slate-950 font-bold',
    shortageCardBg: 'bg-slate-900 bg-gradient-to-b from-cyan-950/30 to-transparent',
    shortageBorder: 'border-cyan-800/60',
    shortageText: 'text-cyan-300',
    coveredCardBg: 'bg-slate-900',
    coveredBorder: 'border-blue-900/50',
    coveredText: 'text-blue-400',
    modalBg: 'bg-slate-900',
    modalBorder: 'border-cyan-900/50',
    modalText: 'text-slate-100'
  },

  'emerald-mint': {
    id: 'emerald-mint',
    name: '3. Emerald Supply Chain & Sage',
    subtitle: 'High-Velocity Positive Inventory & Eco Logistics',
    mode: 'dark',
    previewColor: 'bg-emerald-400',
    appBg: 'bg-zinc-950 text-zinc-100',
    appText: 'text-zinc-100',
    headerBg: 'bg-zinc-900',
    headerBorder: 'border-emerald-900/40',
    headerText: 'text-white',
    logoBg: 'bg-gradient-to-tr from-emerald-400 to-teal-500',
    logoText: 'text-zinc-950',
    badgeBg: 'bg-emerald-500/10',
    badgeText: 'text-emerald-400',
    badgeBorder: 'border-emerald-500/30',
    cardBg: 'bg-zinc-900',
    cardBorder: 'border-zinc-800',
    cardTextHeader: 'text-zinc-400',
    cardTextValue: 'text-emerald-50',
    tableHeaderBg: 'bg-zinc-900',
    tableHeaderText: 'text-emerald-200',
    tableBorder: 'border-zinc-800',
    tableRowHover: 'hover:bg-emerald-950/20',
    priorityBadgeBg: 'bg-zinc-900',
    priorityBadgeText: 'text-emerald-400',
    accentButtonBg: 'bg-emerald-500',
    accentButtonHover: 'hover:bg-emerald-400',
    accentButtonText: 'text-zinc-950 font-bold',
    shortageCardBg: 'bg-zinc-900 bg-gradient-to-b from-emerald-950/20 to-transparent',
    shortageBorder: 'border-emerald-900/50',
    shortageText: 'text-emerald-400',
    coveredCardBg: 'bg-zinc-900',
    coveredBorder: 'border-teal-900/50',
    coveredText: 'text-teal-400',
    modalBg: 'bg-zinc-900',
    modalBorder: 'border-zinc-800',
    modalText: 'text-zinc-100'
  },

  'highvis-orange': {
    id: 'highvis-orange',
    name: '4. Charcoal & High-Vis Orange',
    subtitle: 'High-Visibility Warehouse Safety Terminal Display',
    mode: 'dark',
    previewColor: 'bg-orange-500',
    appBg: 'bg-neutral-950 text-neutral-100',
    appText: 'text-neutral-100',
    headerBg: 'bg-neutral-900',
    headerBorder: 'border-orange-500/40',
    headerText: 'text-white',
    logoBg: 'bg-gradient-to-tr from-orange-500 to-amber-500',
    logoText: 'text-neutral-950',
    badgeBg: 'bg-orange-500/10',
    badgeText: 'text-orange-400',
    badgeBorder: 'border-orange-500/30',
    cardBg: 'bg-neutral-900',
    cardBorder: 'border-neutral-800',
    cardTextHeader: 'text-neutral-400',
    cardTextValue: 'text-white',
    tableHeaderBg: 'bg-neutral-900',
    tableHeaderText: 'text-orange-300',
    tableBorder: 'border-neutral-800',
    tableRowHover: 'hover:bg-orange-950/20',
    priorityBadgeBg: 'bg-neutral-950',
    priorityBadgeText: 'text-orange-400',
    accentButtonBg: 'bg-orange-500',
    accentButtonHover: 'hover:bg-orange-400',
    accentButtonText: 'text-neutral-950 font-bold',
    shortageCardBg: 'bg-neutral-900 bg-gradient-to-b from-orange-950/30 to-transparent',
    shortageBorder: 'border-orange-900/60',
    shortageText: 'text-orange-400',
    coveredCardBg: 'bg-neutral-900',
    coveredBorder: 'border-neutral-800',
    coveredText: 'text-emerald-400',
    modalBg: 'bg-neutral-900',
    modalBorder: 'border-neutral-800',
    modalText: 'text-neutral-100'
  },

  'corporate-navy': {
    id: 'corporate-navy',
    name: '5. Corporate Executive Light Navy',
    subtitle: 'Classic High-Contrast ERP & Boardroom Report Layout',
    mode: 'light',
    previewColor: 'bg-blue-600',
    appBg: 'bg-slate-100 text-slate-900',
    appText: 'text-slate-900',
    headerBg: 'bg-slate-900',
    headerBorder: 'border-slate-800',
    headerText: 'text-white',
    logoBg: 'bg-gradient-to-tr from-blue-600 to-indigo-600',
    logoText: 'text-white',
    badgeBg: 'bg-blue-500/10',
    badgeText: 'text-blue-300',
    badgeBorder: 'border-blue-500/30',
    cardBg: 'bg-white',
    cardBorder: 'border-slate-200',
    cardTextHeader: 'text-slate-500',
    cardTextValue: 'text-slate-900',
    tableHeaderBg: 'bg-slate-900',
    tableHeaderText: 'text-slate-200',
    tableBorder: 'border-slate-200',
    tableRowHover: 'hover:bg-slate-50',
    priorityBadgeBg: 'bg-blue-900',
    priorityBadgeText: 'text-blue-200',
    accentButtonBg: 'bg-blue-600',
    accentButtonHover: 'hover:bg-blue-700',
    accentButtonText: 'text-white font-bold',
    shortageCardBg: 'bg-amber-50/50',
    shortageBorder: 'border-amber-200',
    shortageText: 'text-amber-700',
    coveredCardBg: 'bg-emerald-50/50',
    coveredBorder: 'border-emerald-200',
    coveredText: 'text-emerald-700',
    modalBg: 'bg-white',
    modalBorder: 'border-slate-200',
    modalText: 'text-slate-900'
  },

  'obsidian-gold': {
    id: 'obsidian-gold',
    name: '6. Obsidian Black & Metallic Gold',
    subtitle: 'VIP Export Executive & Luxury Dark Aesthetic',
    mode: 'dark',
    previewColor: 'bg-yellow-500',
    appBg: 'bg-stone-950 text-stone-100',
    appText: 'text-stone-100',
    headerBg: 'bg-stone-900',
    headerBorder: 'border-yellow-600/30',
    headerText: 'text-yellow-100',
    logoBg: 'bg-gradient-to-tr from-yellow-500 to-amber-600',
    logoText: 'text-stone-950',
    badgeBg: 'bg-yellow-500/10',
    badgeText: 'text-yellow-400',
    badgeBorder: 'border-yellow-500/30',
    cardBg: 'bg-stone-900',
    cardBorder: 'border-stone-800',
    cardTextHeader: 'text-stone-400',
    cardTextValue: 'text-yellow-200',
    tableHeaderBg: 'bg-stone-900',
    tableHeaderText: 'text-yellow-300',
    tableBorder: 'border-stone-800',
    tableRowHover: 'hover:bg-yellow-950/20',
    priorityBadgeBg: 'bg-stone-950',
    priorityBadgeText: 'text-yellow-400',
    accentButtonBg: 'bg-yellow-500',
    accentButtonHover: 'hover:bg-yellow-400',
    accentButtonText: 'text-stone-950 font-bold',
    shortageCardBg: 'bg-stone-900 bg-gradient-to-b from-amber-950/30 to-transparent',
    shortageBorder: 'border-amber-900/60',
    shortageText: 'text-yellow-400',
    coveredCardBg: 'bg-stone-900',
    coveredBorder: 'border-stone-800',
    coveredText: 'text-emerald-400',
    modalBg: 'bg-stone-900',
    modalBorder: 'border-yellow-600/30',
    modalText: 'text-stone-100'
  },

  'nordic-indigo': {
    id: 'nordic-indigo',
    name: '7. Nordic Porcelain & Muted Indigo',
    subtitle: 'Minimalist Scandinavian Clean Layout & Cool Tones',
    mode: 'light',
    previewColor: 'bg-indigo-500',
    appBg: 'bg-slate-50 text-slate-800',
    appText: 'text-slate-800',
    headerBg: 'bg-indigo-950',
    headerBorder: 'border-indigo-900',
    headerText: 'text-white',
    logoBg: 'bg-indigo-500',
    logoText: 'text-white',
    badgeBg: 'bg-indigo-500/10',
    badgeText: 'text-indigo-300',
    badgeBorder: 'border-indigo-500/30',
    cardBg: 'bg-white',
    cardBorder: 'border-slate-200',
    cardTextHeader: 'text-slate-500',
    cardTextValue: 'text-slate-900',
    tableHeaderBg: 'bg-indigo-950',
    tableHeaderText: 'text-indigo-100',
    tableBorder: 'border-slate-200',
    tableRowHover: 'hover:bg-indigo-50/50',
    priorityBadgeBg: 'bg-indigo-950',
    priorityBadgeText: 'text-indigo-200',
    accentButtonBg: 'bg-indigo-600',
    accentButtonHover: 'hover:bg-indigo-500',
    accentButtonText: 'text-white font-bold',
    shortageCardBg: 'bg-amber-50/40',
    shortageBorder: 'border-amber-200',
    shortageText: 'text-amber-700',
    coveredCardBg: 'bg-slate-100/60',
    coveredBorder: 'border-slate-200',
    coveredText: 'text-emerald-600',
    modalBg: 'bg-white',
    modalBorder: 'border-slate-200',
    modalText: 'text-slate-900'
  },

  'cyber-matrix': {
    id: 'cyber-matrix',
    name: '8. Cyber Grid Matrix',
    subtitle: 'Futuristic Supply Chain Terminal (Pure Pitch Black & Lime)',
    mode: 'dark',
    previewColor: 'bg-green-400',
    appBg: 'bg-black text-green-400',
    appText: 'text-green-400',
    headerBg: 'bg-zinc-950',
    headerBorder: 'border-green-500/50',
    headerText: 'text-green-300',
    logoBg: 'bg-green-500',
    logoText: 'text-black',
    badgeBg: 'bg-green-500/10',
    badgeText: 'text-green-400',
    badgeBorder: 'border-green-500/30',
    cardBg: 'bg-zinc-950',
    cardBorder: 'border-green-900/60',
    cardTextHeader: 'text-green-600',
    cardTextValue: 'text-green-300',
    tableHeaderBg: 'bg-zinc-950',
    tableHeaderText: 'text-green-400',
    tableBorder: 'border-green-900/60',
    tableRowHover: 'hover:bg-green-950/30',
    priorityBadgeBg: 'bg-black',
    priorityBadgeText: 'text-green-300',
    accentButtonBg: 'bg-green-500',
    accentButtonHover: 'hover:bg-green-400',
    accentButtonText: 'text-black font-bold',
    shortageCardBg: 'bg-zinc-950 bg-gradient-to-b from-amber-950/40 to-transparent',
    shortageBorder: 'border-amber-700',
    shortageText: 'text-amber-400',
    coveredCardBg: 'bg-zinc-950',
    coveredBorder: 'border-green-900',
    coveredText: 'text-green-400',
    modalBg: 'bg-black',
    modalBorder: 'border-green-500/50',
    modalText: 'text-green-300'
  },

  'copper-espresso': {
    id: 'copper-espresso',
    name: '9. Warm Sand & Copper Espresso',
    subtitle: 'Craft Heritage Manufacturing & Natural Materials Style',
    mode: 'light',
    previewColor: 'bg-amber-700',
    appBg: 'bg-[#f7f4ef] text-stone-900',
    appText: 'text-stone-900',
    headerBg: 'bg-stone-900',
    headerBorder: 'border-amber-800/40',
    headerText: 'text-amber-100',
    logoBg: 'bg-gradient-to-tr from-amber-700 to-amber-800',
    logoText: 'text-amber-100',
    badgeBg: 'bg-amber-700/10',
    badgeText: 'text-amber-300',
    badgeBorder: 'border-amber-700/30',
    cardBg: 'bg-[#ffffff]',
    cardBorder: 'border-stone-200',
    cardTextHeader: 'text-stone-500',
    cardTextValue: 'text-stone-900',
    tableHeaderBg: 'bg-stone-900',
    tableHeaderText: 'text-amber-200',
    tableBorder: 'border-stone-200',
    tableRowHover: 'hover:bg-amber-50/50',
    priorityBadgeBg: 'bg-amber-900',
    priorityBadgeText: 'text-amber-200',
    accentButtonBg: 'bg-amber-700',
    accentButtonHover: 'hover:bg-amber-800',
    accentButtonText: 'text-white font-bold',
    shortageCardBg: 'bg-amber-100/60',
    shortageBorder: 'border-amber-300',
    shortageText: 'text-amber-900',
    coveredCardBg: 'bg-emerald-50/60',
    coveredBorder: 'border-emerald-200',
    coveredText: 'text-emerald-800',
    modalBg: 'bg-[#fbf9f5]',
    modalBorder: 'border-stone-300',
    modalText: 'text-stone-900'
  },

  'royal-sapphire': {
    id: 'royal-sapphire',
    name: '10. Royal Sapphire & Sunset Coral',
    subtitle: 'SaaS Executive Deep Sapphire Navy with Coral Highlights',
    mode: 'dark',
    previewColor: 'bg-indigo-600',
    appBg: 'bg-[#0b132b] text-slate-100',
    appText: 'text-slate-100',
    headerBg: 'bg-[#1c2541]',
    headerBorder: 'border-indigo-800/50',
    headerText: 'text-white',
    logoBg: 'bg-gradient-to-tr from-indigo-500 to-rose-500',
    logoText: 'text-white',
    badgeBg: 'bg-rose-500/10',
    badgeText: 'text-rose-300',
    badgeBorder: 'border-rose-500/30',
    cardBg: 'bg-[#1c2541]',
    cardBorder: 'border-indigo-900/60',
    cardTextHeader: 'text-indigo-200/70',
    cardTextValue: 'text-white',
    tableHeaderBg: 'bg-[#1c2541]',
    tableHeaderText: 'text-indigo-200',
    tableBorder: 'border-indigo-900/60',
    tableRowHover: 'hover:bg-indigo-950/40',
    priorityBadgeBg: 'bg-[#0b132b]',
    priorityBadgeText: 'text-rose-400',
    accentButtonBg: 'bg-rose-500',
    accentButtonHover: 'hover:bg-rose-400',
    accentButtonText: 'text-white font-bold',
    shortageCardBg: 'bg-[#1c2541] bg-gradient-to-b from-rose-950/30 to-transparent',
    shortageBorder: 'border-rose-800/60',
    shortageText: 'text-rose-300',
    coveredCardBg: 'bg-[#1c2541]',
    coveredBorder: 'border-indigo-800/50',
    coveredText: 'text-emerald-400',
    modalBg: 'bg-[#1c2541]',
    modalBorder: 'border-indigo-800/50',
    modalText: 'text-slate-100'
  },

  'paper-slate': {
    id: 'paper-slate',
    name: '11. Architectural Paper & Dark Slate',
    subtitle: 'High-Contrast Clean White Canvas & Precision Charcoal Drafting Lines',
    mode: 'light',
    previewColor: 'bg-slate-700',
    appBg: 'bg-[#fcfcfd] text-slate-900',
    appText: 'text-slate-900',
    headerBg: 'bg-slate-900',
    headerBorder: 'border-slate-800',
    headerText: 'text-white',
    logoBg: 'bg-slate-800',
    logoText: 'text-white',
    badgeBg: 'bg-slate-700/20',
    badgeText: 'text-slate-300',
    badgeBorder: 'border-slate-600/30',
    cardBg: 'bg-white',
    cardBorder: 'border-slate-200',
    cardTextHeader: 'text-slate-500',
    cardTextValue: 'text-slate-900',
    tableHeaderBg: 'bg-slate-900',
    tableHeaderText: 'text-slate-200',
    tableBorder: 'border-slate-200',
    tableRowHover: 'hover:bg-slate-100/70',
    priorityBadgeBg: 'bg-slate-900',
    priorityBadgeText: 'text-slate-100',
    accentButtonBg: 'bg-slate-900',
    accentButtonHover: 'hover:bg-slate-800',
    accentButtonText: 'text-white font-bold',
    shortageCardBg: 'bg-amber-50/70',
    shortageBorder: 'border-amber-300',
    shortageText: 'text-amber-800',
    coveredCardBg: 'bg-slate-50',
    coveredBorder: 'border-slate-200',
    coveredText: 'text-emerald-700',
    modalBg: 'bg-white',
    modalBorder: 'border-slate-300',
    modalText: 'text-slate-900'
  },

  'pacific-teal': {
    id: 'pacific-teal',
    name: '12. Pacific Coast Teal & Warm Sand',
    subtitle: 'Oceanic Maritime Freight & Bright Coastal Logistics',
    mode: 'light',
    previewColor: 'bg-teal-600',
    appBg: 'bg-[#f4f8f8] text-teal-950',
    appText: 'text-teal-950',
    headerBg: 'bg-teal-950',
    headerBorder: 'border-teal-900',
    headerText: 'text-teal-50',
    logoBg: 'bg-gradient-to-tr from-teal-500 to-cyan-500',
    logoText: 'text-slate-950',
    badgeBg: 'bg-teal-500/10',
    badgeText: 'text-teal-300',
    badgeBorder: 'border-teal-500/30',
    cardBg: 'bg-white',
    cardBorder: 'border-teal-100',
    cardTextHeader: 'text-teal-700/80',
    cardTextValue: 'text-teal-950',
    tableHeaderBg: 'bg-teal-950',
    tableHeaderText: 'text-teal-100',
    tableBorder: 'border-teal-100',
    tableRowHover: 'hover:bg-teal-50/60',
    priorityBadgeBg: 'bg-teal-900',
    priorityBadgeText: 'text-teal-200',
    accentButtonBg: 'bg-teal-600',
    accentButtonHover: 'hover:bg-teal-700',
    accentButtonText: 'text-white font-bold',
    shortageCardBg: 'bg-amber-50/60',
    shortageBorder: 'border-amber-200',
    shortageText: 'text-amber-800',
    coveredCardBg: 'bg-teal-50/50',
    coveredBorder: 'border-teal-200',
    coveredText: 'text-teal-800',
    modalBg: 'bg-white',
    modalBorder: 'border-teal-200',
    modalText: 'text-teal-950'
  },

  'sunset-terracotta': {
    id: 'sunset-terracotta',
    name: '13. Sunset Terracotta & Warm Quartz',
    subtitle: 'Warm Earth Tones & Mediterranean Warehouse Executive',
    mode: 'light',
    previewColor: 'bg-orange-600',
    appBg: 'bg-[#faf6f2] text-stone-900',
    appText: 'text-stone-900',
    headerBg: 'bg-[#2d1b18]',
    headerBorder: 'border-stone-800',
    headerText: 'text-amber-50',
    logoBg: 'bg-gradient-to-tr from-orange-600 to-amber-600',
    logoText: 'text-white',
    badgeBg: 'bg-orange-500/10',
    badgeText: 'text-orange-300',
    badgeBorder: 'border-orange-500/30',
    cardBg: 'bg-white',
    cardBorder: 'border-stone-200',
    cardTextHeader: 'text-stone-500',
    cardTextValue: 'text-stone-900',
    tableHeaderBg: 'bg-[#2d1b18]',
    tableHeaderText: 'text-amber-100',
    tableBorder: 'border-stone-200',
    tableRowHover: 'hover:bg-orange-50/40',
    priorityBadgeBg: 'bg-[#2d1b18]',
    priorityBadgeText: 'text-amber-300',
    accentButtonBg: 'bg-orange-600',
    accentButtonHover: 'hover:bg-orange-700',
    accentButtonText: 'text-white font-bold',
    shortageCardBg: 'bg-amber-50/70',
    shortageBorder: 'border-amber-300',
    shortageText: 'text-amber-900',
    coveredCardBg: 'bg-stone-50',
    coveredBorder: 'border-stone-200',
    coveredText: 'text-emerald-700',
    modalBg: 'bg-white',
    modalBorder: 'border-stone-200',
    modalText: 'text-stone-900'
  },

  'forest-sage': {
    id: 'forest-sage',
    name: '14. Alpine Forest & Fresh Sage',
    subtitle: 'Eco-Certified Supply Chain & Fresh Natural Green',
    mode: 'light',
    previewColor: 'bg-emerald-700',
    appBg: 'bg-[#f3f7f4] text-emerald-950',
    appText: 'text-emerald-950',
    headerBg: 'bg-[#0f2e1b]',
    headerBorder: 'border-emerald-900',
    headerText: 'text-emerald-50',
    logoBg: 'bg-gradient-to-tr from-emerald-500 to-green-600',
    logoText: 'text-white',
    badgeBg: 'bg-emerald-500/10',
    badgeText: 'text-emerald-300',
    badgeBorder: 'border-emerald-500/30',
    cardBg: 'bg-white',
    cardBorder: 'border-emerald-100',
    cardTextHeader: 'text-emerald-800/70',
    cardTextValue: 'text-emerald-950',
    tableHeaderBg: 'bg-[#0f2e1b]',
    tableHeaderText: 'text-emerald-100',
    tableBorder: 'border-emerald-100',
    tableRowHover: 'hover:bg-emerald-50/60',
    priorityBadgeBg: 'bg-[#0f2e1b]',
    priorityBadgeText: 'text-emerald-200',
    accentButtonBg: 'bg-emerald-700',
    accentButtonHover: 'hover:bg-emerald-800',
    accentButtonText: 'text-white font-bold',
    shortageCardBg: 'bg-amber-50/60',
    shortageBorder: 'border-amber-200',
    shortageText: 'text-amber-800',
    coveredCardBg: 'bg-emerald-50/50',
    coveredBorder: 'border-emerald-200',
    coveredText: 'text-emerald-800',
    modalBg: 'bg-white',
    modalBorder: 'border-emerald-200',
    modalText: 'text-emerald-950'
  },

  'violet-platinum': {
    id: 'violet-platinum',
    name: '15. Violet Platinum & Bright Orchid',
    subtitle: 'Modern Light Enterprise Tech with Vivid Violet Accents',
    mode: 'light',
    previewColor: 'bg-purple-600',
    appBg: 'bg-[#f7f5fa] text-slate-900',
    appText: 'text-slate-900',
    headerBg: 'bg-[#1e1035]',
    headerBorder: 'border-purple-900',
    headerText: 'text-purple-50',
    logoBg: 'bg-gradient-to-tr from-purple-500 to-indigo-500',
    logoText: 'text-white',
    badgeBg: 'bg-purple-500/10',
    badgeText: 'text-purple-300',
    badgeBorder: 'border-purple-500/30',
    cardBg: 'bg-white',
    cardBorder: 'border-purple-100',
    cardTextHeader: 'text-purple-900/60',
    cardTextValue: 'text-slate-900',
    tableHeaderBg: 'bg-[#1e1035]',
    tableHeaderText: 'text-purple-100',
    tableBorder: 'border-purple-100',
    tableRowHover: 'hover:bg-purple-50/50',
    priorityBadgeBg: 'bg-[#1e1035]',
    priorityBadgeText: 'text-purple-200',
    accentButtonBg: 'bg-purple-600',
    accentButtonHover: 'hover:bg-purple-700',
    accentButtonText: 'text-white font-bold',
    shortageCardBg: 'bg-amber-50/60',
    shortageBorder: 'border-amber-200',
    shortageText: 'text-amber-800',
    coveredCardBg: 'bg-purple-50/40',
    coveredBorder: 'border-purple-200',
    coveredText: 'text-emerald-700',
    modalBg: 'bg-white',
    modalBorder: 'border-purple-200',
    modalText: 'text-slate-900'
  }
};
